spring.datasource.url=jdbc:postgresql://localhost:5432/ride_db
spring.datasource.username=postgres
spring.datasource.password=ritik2006
spring.datasource.driver-class-name=org.postgresql.Driver

# For modern web apps:
server.port=8080
spring.jackson.serialization.indent_output=true
